### ISSUE TITLE
Docker manipulating

### ISSUE THREAD

**Issue by arckosfr** [saedbox/Saedbox#17]
- Create container
- Stop/Start Container
- Delete Container
- Container ps
- List all container

**Comment by arckosfr** [comment]
Faut voir ce qu'on appelle "Update Container"
Genre je veux changer un port ou autre ?
Si oui en gros "Remove/Create/Run" ?

**Comment by farfeduc** [comment]
Yep ! Avec l'ajout ou la suppression de labels.

**Comment by arckosfr** [comment]
C est a dire label ?⁣

Envoyé par BlueMail ​

Le 10 déc. 2016 22:31, à 22:31, Adrien Girardeau <notifications@github.com> a écrit:

**Comment by farfeduc** [comment]
Pour que les container docker soit le backend de certaines routes, il faut leur mettre des labels afin que traefik fonctionne correctement. Donc lors d'une "update" il faut pouvoir changer un ou plusieurs labels par rapport à l'ancien container.

**Comment by arckosfr** [comment]
Je pense qu'en passant l'argument via ca : 
```js
docker.new = function(name, cb) {
    var optsc = {
        'Hostname': '',
        'User': '',
        'AttachStdin': true,
        'AttachStdout': true,
        'AttachStderr': true,
        'Tty': true,
        'OpenStdin': true,
        'StdinOnce': false,
        'Env': null,
        'Cmd': [],
        'Dns': [],
        'Image': name,
        'Volumes': {},
        'VolumesFrom': []
    };
    docker.createContainer(optsc, function(err, container) {
```

C'est possible

**Comment by farfeduc** [comment]
Mais là il y a pas de labels non ?
