### ISSUE TITLE
System info API

### ISSUE THREAD

**Issue by arckosfr** [saedbox/Saedbox#18]
Add possibility for API to return system info

**Comment by arckosfr** [comment]
On pourra surement utiliser les websocket pour avoir un meilleur taux de rafraichissement

**Comment by arckosfr** [comment]
2ebb02d68b7e25cee103a4c8b05b7a67ba5d57f5

**Comment by Hydrog3n** [comment]
Les websockets c'est vraiment quand tu veux du live. Un pooling sur l'api toute les 5sec c'est pas mal déjà et ça enlève la partie websocket qui rajoute un peu de complexité.

**Comment by arckosfr** [comment]
@Hydrog3n Oui c'est ce qui est prévu, mais genre pour les stats reseaux on sais pas si c'est mieux d'avoir tu temps réel ou de la requete API a gogo 🎉

**Comment by Hydrog3n** [comment]
Il faut voir si c'est chiant de rajouter un websocket je pense que c'est ça qui va faire pencher la balance :D

**Comment by farfeduc** [comment]
Avec socket.io, c'est vraiment simple. On pourra le mettre en place facilement.
